name: auto_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/static/Manrope-Regular.ttf
    - family: ManropeBold
      fonts:
        - asset: assets/fonts/static/Manrope-Bold.ttf
    - family: ManropeExtraBold
      fonts:
        - asset: assets/fonts/static/Manrope-ExtraBold.ttf

